version: "3.9"
services:
  gocloud:
    build:
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - db
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "gocloud"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"