version: "3.9"
services:
  gocloud:
    build:
      context: .
    env_file:
      - ".env"
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "gocloud"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432